-- =================================================================
-- NGỌC CHÂU CINEMA — SUPABASE DATABASE SCHEMA & INITIAL SEED DATA
-- Hướng dẫn: Copy toàn bộ nội dung file này và Dán (Paste) vào Supabase SQL Editor
-- Link: https://supabase.com/dashboard/project/emvdkwrgxvzvoqriqtis/sql/new
-- =================================================================

-- 1. XOÁ BẢNG CŨ (NẾU CÓ)
DROP TABLE IF EXISTS booking_seats CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS showtimes CASCADE;
DROP TABLE IF EXISTS seats CASCADE;
DROP TABLE IF EXISTS screens CASCADE;
DROP TABLE IF EXISTS cinemas CASCADE;
DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS food_items CASCADE;
DROP TABLE IF EXISTS promotions CASCADE;

-- 2. TẠO CÁC BẢNG DỮ LIỆU CHUẨN SUPABASE

-- Bảng Phim Chiếu Rạp (Movies)
CREATE TABLE movies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  poster_url TEXT,
  backdrop_url TEXT,
  genre TEXT,
  duration_minutes INTEGER DEFAULT 120,
  age_rating TEXT DEFAULT 'P',
  release_date DATE,
  status TEXT DEFAULT 'now_showing',
  approval_status TEXT DEFAULT 'approved',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Bảng Cụm Rạp Chiếu (Cinemas)
CREATE TABLE cinemas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  city TEXT,
  status TEXT DEFAULT 'active'
);

-- Bảng Phòng Chiếu (Screens)
CREATE TABLE screens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cinema_id BIGINT REFERENCES cinemas(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  total_seats INTEGER DEFAULT 60
);

-- Bảng Ghế Xem Phim (Seats)
CREATE TABLE seats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  screen_id BIGINT REFERENCES screens(id) ON DELETE CASCADE,
  seat_code TEXT NOT NULL,
  row_name TEXT NOT NULL,
  seat_number INTEGER NOT NULL,
  seat_type TEXT DEFAULT 'standard',
  price_multiplier NUMERIC DEFAULT 1.0
);

-- Bảng Suất Chiếu Phim (Showtimes)
CREATE TABLE showtimes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id BIGINT REFERENCES movies(id) ON DELETE CASCADE,
  screen_id BIGINT REFERENCES screens(id) ON DELETE CASCADE,
  show_date DATE NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT DEFAULT '2 tiếng',
  base_price NUMERIC NOT NULL DEFAULT 110000,
  status TEXT DEFAULT 'active',
  approval_status TEXT DEFAULT 'approved'
);

-- Bảng Khách Hàng (Customers)
CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  password TEXT DEFAULT '123456',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Bảng Tài Khoản & Phân Quyền Hạn Hệ Thống (Users & Roles)
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user',
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Bảng Đồ Ăn & Bắp Nước F&B (Food Items)
CREATE TABLE food_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  category TEXT DEFAULT 'combo',
  image_url TEXT
);

-- Bảng Mã Giảm Giá Ưu Đãi (Promotions)
CREATE TABLE promotions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  description TEXT,
  discount_type TEXT NOT NULL DEFAULT 'percentage',
  discount_value NUMERIC NOT NULL,
  min_order_amount NUMERIC DEFAULT 0
);

-- Bảng Đơn Đặt Vé (Bookings)
CREATE TABLE bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_code TEXT UNIQUE NOT NULL,
  customer_id BIGINT,
  showtime_id BIGINT REFERENCES showtimes(id) ON DELETE CASCADE,
  total_amount NUMERIC NOT NULL,
  ticket_amount NUMERIC DEFAULT 0,
  food_amount NUMERIC DEFAULT 0,
  discount_amount NUMERIC DEFAULT 0,
  discount_code TEXT,
  food_details TEXT,
  payment_method TEXT DEFAULT 'momo',
  status TEXT DEFAULT 'confirmed',
  payment_status TEXT DEFAULT 'paid',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Bảng Ghế Đã Đặt (Booking Seats)
CREATE TABLE booking_seats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT REFERENCES bookings(id) ON DELETE CASCADE,
  seat_id BIGINT REFERENCES seats(id) ON DELETE CASCADE,
  price NUMERIC NOT NULL
);

-- 3. BẬT QUYỀN TRUY CẬP CÔNG KHAI (ROW LEVEL SECURITY POLICIES)

ALTER TABLE movies ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Movies" ON movies FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE cinemas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Cinemas" ON cinemas FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE screens ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Screens" ON screens FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE seats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Seats" ON seats FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE showtimes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Showtimes" ON showtimes FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Customers" ON customers FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Users" ON users FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE food_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Food" ON food_items FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE promotions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Promotions" ON promotions FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Bookings" ON bookings FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE booking_seats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Booking Seats" ON booking_seats FOR ALL USING (true) WITH CHECK (true);

-- 4. KHỞI TẠO DỮ LIỆU MẪU (SEED DATA)

-- Khởi tạo 14 Tài khoản & Phân quyền
INSERT INTO users (full_name, email, phone, password, role) VALUES
('Quản Trị Viên Hệ Thống', 'admin@demo.com', '0900000000', 'admin123', 'admin'),
('Quản Trị Admin', 'admin', '0900000001', 'admin123', 'admin'),
('Khách Hàng User 1', 'user1@demo.com', '0911000001', '123456', 'user'),
('Khách Hàng User 2', 'user2@demo.com', '0911000002', '123456', 'user'),
('Khách Hàng User 3', 'user3@demo.com', '0911000003', '123456', 'user'),
('Khách Hàng User 4', 'user4@demo.com', '0911000004', '123456', 'user'),
('Khách Hàng User 5', 'user5@demo.com', '0911000005', '123456', 'user'),
('Nhân Viên Staff 1', 'staff1@demo.com', '0922000001', '123456', 'staff'),
('Nhân Viên Staff 2', 'staff2@demo.com', '0922000002', '123456', 'staff'),
('Nhân Viên Staff 3', 'staff3@demo.com', '0922000003', '123456', 'staff'),
('Nhân Viên Staff 4', 'staff4@demo.com', '0922000004', '123456', 'staff'),
('Nhân Viên Staff 5', 'staff5@demo.com', '0922000005', '123456', 'staff'),
('Nhà Tài Trợ NTT 1', 'ntt1@demo.com', '0933000001', '123456', 'sponsor'),
('Nhà Tài Trợ NTT 2', 'ntt2@demo.com', '0933000002', '123456', 'sponsor'),
('Nhà Tài Trợ NTT 3', 'ntt3@demo.com', '0933000003', '123456', 'sponsor');

-- Khởi tạo Danh sách Phim
INSERT INTO movies (title, slug, description, poster_url, backdrop_url, genre, duration_minutes, age_rating, release_date, status, approval_status) VALUES
('Mai', 'mai', 'Câu chuyện cảm động về cuộc đời của Mai...', 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=600&auto=format&fit=crop', 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=1200&auto=format&fit=crop', 'Tâm lý, Tình cảm', 131, 'T18', '2026-02-10', 'now_showing', 'approved'),
('Lật Mặt 7: Một Điều Ước', 'lat-mat-7', 'Hành trình tình thân đầy xúc động...', 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=600&auto=format&fit=crop', 'https://images.unsplash.com/photo-1574267432553-4b4628081c31?q=80&w=1200&auto=format&fit=crop', 'Gia đình, Tâm lý', 138, 'K', '2026-04-26', 'now_showing', 'approved'),
('Dune: Hành Tinh Cát 2', 'dune-2', 'Paul Atreides hợp lực cùng Chani...', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop', 'Hành động, Viễn tưởng', 166, 'T16', '2026-03-01', 'now_showing', 'approved'),
('Godzilla x Kong: Đế Chế Mới', 'godzilla-x-kong', 'Hai đại quái thú huyền thoại hợp lực...', 'https://images.unsplash.com/photo-1568876694728-451bbf694b83?q=80&w=600&auto=format&fit=crop', 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1200&auto=format&fit=crop', 'Hành động, Quái thú', 115, 'T13', '2026-03-29', 'now_showing', 'approved'),
('Kung Fu Panda 4', 'kung-fu-panda-4', 'Po phải tìm kiếm và huấn luyện...', 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=600&auto=format&fit=crop', 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?q=80&w=1200&auto=format&fit=crop', 'Hoạt hình, Hài hước', 94, 'P', '2026-03-08', 'now_showing', 'approved'),
('Exhuma: Quật Mộ Trùng Ma', 'exhuma', 'Hai thầy phong thủy và pháp sư...', 'https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=600&auto=format&fit=crop', 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?q=80&w=1200&auto=format&fit=crop', 'Kinh dị, Bí ẩn', 134, 'T18', '2026-03-15', 'now_showing', 'approved'),
('Deadpool & Wolverine', 'deadpool-and-wolverine', 'Deadpool và Wolverine hợp sức trong trận chiến bảo vệ đa vũ trụ Marvel.', 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=600&auto=format&fit=crop', 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=1200&auto=format&fit=crop', 'Hành động, Hài hước', 127, 'T18', '2026-07-26', 'now_showing', 'approved'),
('Inside Out 2 (Những Mảnh Ghép Cảm Xúc 2)', 'inside-out-2', 'Riley bước vào tuổi dậy thì với sự xuất hiện của những cảm xúc mới.', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop', 'Hoạt hình, Gia đình', 96, 'P', '2026-06-14', 'now_showing', 'approved'),
('Despicable Me 4 (Kẻ Trộm Mặt Trăng 4)', 'despicable-me-4', 'Gru và gia đình đón chào thành viên mới Gru Jr. cùng đội quân Minions.', 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=600&auto=format&fit=crop', 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=1200&auto=format&fit=crop', 'Hoạt hình, Hài hước', 94, 'P', '2026-07-03', 'now_showing', 'approved'),
('Alien: Romulus', 'alien-romulus', 'Một nhóm bạn trẻ dọn dẹp trạm vũ trụ bỏ hoang và đối mặt sinh vật quái dị.', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop', 'Kinh dị, Viễn tưởng', 119, 'T18', '2026-08-16', 'coming_soon', 'approved');

-- Khởi tạo Cụm Rạp
INSERT INTO cinemas (name, address, city) VALUES
('Ngọc Châu Cinema Quận 1', '135 Nguyễn Huệ, Phường Bến Nghé, Quận 1', 'TP. Hồ Chí Minh'),
('Ngọc Châu Cinema Thủ Đức', '216 Võ Văn Ngân, P. Bình Thọ, TP. Thủ Đức', 'TP. Hồ Chí Minh'),
('Ngọc Châu Cinema Cầu Giấy', '241 Xuân Thủy, Q. Cầu Giấy', 'Hà Nội');

-- Khởi tạo Phòng Chiếu
INSERT INTO screens (cinema_id, name, total_seats) VALUES
(1, 'Phòng 01 - IMAX 3D', 60),
(1, 'Phòng 02 - VIP Studio', 60),
(2, 'Phòng 01 - Dolby Atmos', 60),
(3, 'Phòng 01 - Premium 4K', 60);

-- Khởi tạo Mã Giảm Giá
INSERT INTO promotions (code, description, discount_type, discount_value, min_order_amount) VALUES
('NGOCCHAU10', 'Giảm 10% tổng đơn đặt vé & bắp nước', 'percentage', 10, 0),
('VIPCINEMA20', 'Ưu đãi thành viên VIP giảm 20%', 'percentage', 20, 100000),
('TIETKIEM50K', 'Giảm trực tiếp 50.000 ₫ cho đơn từ 150.000 ₫', 'fixed', 50000, 150000);

-- Khởi tạo Đồ Ăn & Bắp Nước
INSERT INTO food_items (name, description, price, category, image_url) VALUES
('Combo Solo Bắp Nước', '1 Bắp ngọt lớn (60oz) + 1 Nước ngọt lớn (32oz)', 89000, 'combo', '🍿'),
('Combo Couple Bắp Nước', '1 Bắp ngọt lớn (60oz) + 2 Nước ngọt lớn (32oz)', 119000, 'combo', '🍿🥤'),
('Combo Party Ngọc Châu', '2 Bắp bơ phô mai lớn + 2 Nước lớn + 1 Snack khoai tây', 159000, 'combo', '🍿🥤🍟'),
('Bắp Rang Phô Mai (L)', 'Bắp rang giòn rụm phủ lớp bột phô mai béo ngậy', 59000, 'popcorn', '🧀'),
('Bắp Rang Bơ Caramel (L)', 'Bắp rang ngọt ngào bọc lớp bơ caramel thơm lừng', 55000, 'popcorn', '🍯'),
('Nước Ngọt Pepsi / Coca (L)', 'Nước ngọt có gas 32oz ướp lạnh sảng khoái', 35000, 'drink', '🥤');

-- Khởi tạo Suất Chiếu
INSERT INTO showtimes (movie_id, screen_id, show_date, start_time, end_time, base_price) VALUES
(1, 1, CURRENT_DATE, '10:00', '2 tiếng', 110000),
(1, 1, CURRENT_DATE, '14:30', '2 tiếng', 110000),
(1, 2, CURRENT_DATE + 1, '18:00', '2 tiếng', 110000),
(2, 2, CURRENT_DATE, '11:15', '2 tiếng', 110000),
(2, 3, CURRENT_DATE + 1, '16:00', '2 tiếng', 110000),
(3, 3, CURRENT_DATE, '13:00', '2 tiếng', 100000),
(4, 4, CURRENT_DATE, '15:30', '2 tiếng', 100000),
(5, 1, CURRENT_DATE + 1, '09:30', '2 tiếng', 100000),
(6, 2, CURRENT_DATE + 1, '20:15', '2 tiếng', 110000),
(7, 3, CURRENT_DATE + 2, '14:00', '2 tiếng', 120000);
